### ISSUE TITLE
HARS site overlap with Peaks

### ISSUE THREAD

**Issue by sudhirjadhao** [hartonen/PeakXus#2]
Dear Sir/Ma'am,

Greetings for the day !!!

I have run PeakXus.
In the output,  I have peaks_with_pwm_hit_*.igv file, which contains the information of HARS site overlap with peaks. In this file, PeakID and HARS cite count (~25000) is same. In the graph, it's showing different HARS site (~25000)  and peaks (~200000).
 
 How I can get all PeakID which are overlapped with HARS cite from Peakxus output

Thank you In advance

Best Regards,
Sudhir

**Comment by hartonen** [comment]
Hi Sudhir,

I am not entirely sure if I understood your question correctly. So the file you mentioned, the peaks_with_pwm_hit_*.igv contains ALL PEAKS THAT OVERLAP with an HARS site. So the fact that in the graph the y-axis value (hits to HARS sites) and x-axis values (total number of peaks) are different just means that not all of the peaks contain a sequence matching to the motif/pwm you are using (which is expected of course). So the file peaks_with_pwm_hit_*.igv does not contain all peaks, only the ones that overlap with an HARS site. The file all_transition_points.igv on the other hand contains all peaks.

Best,
Tuomo

**Comment by sudhirjadhao** [comment]
Dear Tuomo,

Thank you for your reply and valuable time.

I got my answer

Best Regards,
Sudhir
